#!/usr/bin/env python3
"""
Regenerates BlueGLCoreWindowsGnuImpl.S from BlueGLCoreWindowsImpl.S.

BlueGLCoreWindowsImpl.S (produced by bluegl-gen.py) is MASM syntax and needs ml64.exe
(MSVC-only). This script derives a GNU-assembler/COFF equivalent for a non-MSVC Windows
toolchain (e.g. zig cc targeting *-windows-gnu), which has no ml64.exe.

Re-run this whenever bluegl-gen.py is re-run for the 'Windows' platform (i.e. whenever the
GL function list changes), so BlueGLCoreWindowsGnuImpl.S stays in sync with
BlueGLCoreWindowsImpl.S. See bluegl/CMakeLists.txt for how the two are selected.
"""
import os
import re

SELF_DIR = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(SELF_DIR, "src", "BlueGLCoreWindowsImpl.S")
DST = os.path.join(SELF_DIR, "src", "BlueGLCoreWindowsGnuImpl.S")

with open(SRC, "r") as f:
    text = f.read()

names = re.findall(r"extrn __blue_glCore_(\w+): qword", text)
if not names:
    raise SystemExit(f"no 'extrn __blue_glCore_<name>: qword' lines found in {SRC}")

header = (
    "/**********************************************************************************************\n"
    " * Generated by bluegl/gen-windowsgnu-impl.py from BlueGLCoreWindowsImpl.S (MASM original)\n"
    " * DO NOT EDIT\n"
    " *\n"
    " * GNU-assembler/COFF equivalent of the MASM trampolines in BlueGLCoreWindowsImpl.S, for a\n"
    " * non-MSVC Windows toolchain (e.g. zig cc targeting *-windows-gnu) that has no ml64.exe.\n"
    " * Same semantics as the MASM version: load the resolved function pointer out of the\n"
    " * __blue_glCore_<name> global (populated at runtime by BlueGL's lazy loader) directly into\n"
    " * r11, then jump to it - no GOT indirection needed since these are same-link-unit symbols.\n"
    " **********************************************************************************************/\n"
)

parts = [header]
for name in names:
    parts.append(
        f"\n.globl bluegl_{name}\n"
        f"bluegl_{name}:\n"
        f"    mov __blue_glCore_{name}(%rip), %r11\n"
        f"    jmp *%r11\n"
    )

with open(DST, "w", newline="\n") as f:
    f.write("".join(parts))

print(f"wrote {DST} with {len(names)} trampolines")
